// <auto-generated />
using System;
using EmpAppBlazor.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpAppBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220330181846_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpAppBlazor.Shared.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2022, 4, 4, 20, 18, 46, 83, DateTimeKind.Local).AddTicks(5969),
                            Description = "",
                            Name = "Tomason",
                            Number = 17156,
                            Site = "Self-Build"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryDate = new DateTime(2022, 5, 4, 20, 18, 46, 83, DateTimeKind.Local).AddTicks(6007),
                            Description = "",
                            Name = "Ellesar",
                            Number = 14104,
                            Site = "Self-Build"
                        },
                        new
                        {
                            Id = 3,
                            DeliveryDate = new DateTime(2022, 4, 3, 20, 18, 46, 83, DateTimeKind.Local).AddTicks(6011),
                            Description = "This project is on hold now.",
                            Name = "Clark",
                            Number = 21201,
                            Site = "KTS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
